---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitea

labels:
  - includeSelectors: true
    pairs:
      app: gitea

resources:
  - serviceaccount.yaml
  - storage.yaml
  - db-headless.yaml
  - db-pvc.yaml
  - db-statefulset.yaml
  - db-svc.yaml
  - redis-headless.yaml
  - redis-pvc.yaml
  - redis-statefulset.yaml
  - redis-svc.yaml
  - gitea-headless.yaml
  - gitea-pvc.yaml
  - gitea-statefulset.yaml
  - gitea-http-svc.yaml
  - gitea-ssh-svc.yaml
