apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: git-rwx-dev
spec:
  secretName: tls-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: 'git.rwx.dev'
  dnsNames:
  - 'git.rwx.dev'
