---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitea

images:
  - name: gitea-image
    newName: gitea/gitea
    newTag: "1.20"
  - name: postgres-image
    newName: postgres
    newTag: 14-alpine
  - name: redis-image
    newName: redis
    newTag: latest

labels:
  - includeSelectors: true
    pairs:
      app: gitea

configMapGenerator:
  - name: gitea-env
    envs:
      - config/gitea.env
    

patches:
  - path: storage.yaml
  - path: db-statefulset.yaml
  - path: gitea-statefulset.yaml
  # - path: redis-statefulset.yaml

resources:
  - ../../base
  - secrets.yaml
  - certificate.yaml
  - ingress.yaml
