---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gogs

images:
  - name: gogs-image
    newName: gogs/gogs
    newTag: latest
  - name: postgres-image
    newName: postgres
    newTag: latest
  - name: redis-image
    newName: redis
    newTag: latest

labels:
  - includeSelectors: true
    pairs:
      app: gogs

configMapGenerator:
  - name: app-ini
    files:
      - config/app.ini

patches:
  - path: storage.yaml
  - path: gogs-db-statefulset.yaml
  - path: gogs-statefulset.yaml
  # - path: redis-statefulset.yaml
  - patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: db-env
      $patch: delete

resources:
  - ../../base
  - secrets.yaml
  - certificate.yaml
  - ingress.yaml
