---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gitea-env
spec:
  provider: vault
  secretObjects:
  - secretName: gitea-env
    type: Opaque
    data:
      - key: POSTGRES_USER
        objectName: POSTGRES_USER
      - key: POSTGRES_PASSWORD
        objectName: POSTGRES_PASSWORD
      - key: POSTGRES_DB
        objectName: POSTGRES_DB
      - key: GITEA_mailer_PASSWD
        objectName: GITEA_mailer_PASSWD
      - key: GITEA_server_LFS_JWS_SECRET
        objectName: GITEA_server_LFS_JWS_SECRET
      - key: GITEA_database_PASSWD
        objectName: GITEA_database_PASSWD
      - key: GITEA_security_SECRET_KEY
        objectName: GITEA_security_SECRET_KEY
      - key: GITEA_security_INTERNAL_TOKEN
        objectName: GITEA_security_INTERNAL_TOKEN
  parameters:
    roleName: gitea
    vaultAddress: https://vlt.rwx.dev
    vaultKubernetesMountPath: k8s-skydive
    objects: |
      - objectName: POSTGRES_USER
        secretPath: secrets/data/gitea
        secretKey: POSTGRES_USER
      - objectName: POSTGRES_PASSWORD
        secretPath: secrets/data/gitea
        secretKey: POSTGRES_PASSWORD
      - objectName: POSTGRES_DB
        secretPath: secrets/data/gitea
        secretKey: POSTGRES_DB
      - objectName: GITEA_mailer_PASSWD
        secretPath: secrets/data/gitea
        secretKey: GITEA_mailer_PASSWD
      - objectName: GITEA_server_LFS_JWS_SECRET
        secretPath: secrets/data/gitea
        secretKey: GITEA_server_LFS_JWS_SECRET
      - objectName: GITEA_database_PASSWD
        secretPath: secrets/data/gitea
        secretKey: GITEA_database_PASSWD
      - objectName: GITEA_security_SECRET_KEY
        secretPath: secrets/data/gitea
        secretKey: GITEA_security_SECRET_KEY
      - objectName: GITEA_security_INTERNAL_TOKEN
        secretPath: secrets/data/gitea
        secretKey: GITEA_security_INTERNAL_TOKEN
      