---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-env
spec:
  provider: vault
  secretObjects:
  - secretName: db-env
    type: Opaque
    data:
      - key: POSTGRES_USER
        objectName: POSTGRES_USER
      - key: POSTGRES_PASSWORD
        objectName: POSTGRES_PASSWORD
      - key: POSTGRES_DB
        objectName: POSTGRES_DB
      - key: SMTP_TOKEN
        objectName: SMTP_TOKEN
      - key: REDIS_PASSWORD
        objectName: REDIS_PASSWORD
  parameters:
    roleName: gogs
    vaultAddress: https://vlt.rwx.dev
    vaultKubernetesMountPath: k8s-skydive
    objects: |
      - objectName: POSTGRES_USER
        secretPath: secrets/data/gogs
        secretKey: POSTGRES_USER
      - objectName: POSTGRES_PASSWORD
        secretPath: secrets/data/gogs
        secretKey: POSTGRES_PASSWORD
      - objectName: POSTGRES_DB
        secretPath: secrets/data/gogs
        secretKey: POSTGRES_DB
      - objectName: SMTP_TOKEN
        secretPath: secrets/data/gogs
        secretKey: SMTP_TOKEN
      - objectName: REDIS_PASSWORD
        secretPath: secrets/data/gogs
        secretKey: REDIS_PASSWORD